version: '2'

services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.development
    #command: '/bin/bash -c "rm -rf tmp/pids/*; bundle exec rails s -b 0.0.0.0"'
    command: 'passenger start --max-pool-size=1'
    volumes:
      - .:/home/app/pg2rs
    ports:
      - "3000:3000"
    links:
      - db
      - redis

  sidekiq:
    build:
      context: .
      dockerfile: docker/app/Dockerfile.development
    command: 'bundle exec sidekiq'
    volumes:
      - .:/home/app/pg2rs
    links:
      - db
      - redis
