db:
  image: 'postgres:9.5'
  volumes:
    - /var/pg2rs/production/pgdata:/var/lib/postgresql/data

web:
  ports:
    - '80:80'
  image: 'onthespot/wifimap-pg2rs:latest'
  restart: always
  tags:
    - wifimap-utility
  target_num_containers: 1
  links:
    - db
    - redis

redis:
  image: redis
  tags:
    - wifimap-utility
  target_num_containers: 1

sidekiq:
  image: 'onthespot/wifimap-pg2rs:latest'
  command: bundle exec sidekiq
  target_num_containers: 1
  restart: always
  links:
    - db
    - redis
  tags:
    - wifimap-utility
