db:
  image: 'postgres:9.5'
  volumes:
    - /var/pg2rs/production/pgdata:/var/lib/postgresql/data
  tags:
    - utility

web:
  ports:
    - '80:80'
  image: 'wifimap/pg2rs:latest'
  restart: always
  command: /bin/sh -c "bundle exec whenever --update-crontab pg2rs --set 'environment=production' && /sbin/my_init"
  tags:
    - utility
  target_num_containers: 1
  links:
    - db
    - redis

redis:
  image: redis
  tags:
    - utility
  target_num_containers: 1

sidekiq:
  image: 'wifimap/pg2rs:latest'
  command: bundle exec sidekiq -C config/sidekiq.yml
  target_num_containers: 1
  restart: always
  links:
    - db
    - redis
  tags:
    - utility
